import { Order, Product, BakongSettings } from "../types";

/**
 * Filter orders for a specific date (YYYY-MM-DD)
 */
export function getOrdersByDate(orders: Order[], dateStr: string): Order[] {
  return orders.filter(order => {
    if (order.status === "Voided") return false;
    const orderDatePart = order.date.split("T")[0];
    return orderDatePart === dateStr;
  });
}

/**
 * Generates an HTML-formatted message summarizing sales and inventory metrics for a given date
 */
export function generateDailyReportHTML(orders: Order[], products: Product[], settings: BakongSettings, dateStr: string): string {
  const dayOrders = getOrdersByDate(orders, dateStr);
  
  // Calculate general financial stats
  let netSales = 0;
  let totalOrders = dayOrders.length;
  let cogs = 0;
  let cashSales = 0;
  let cashCount = 0;
  let bakongSales = 0;
  let bakongCount = 0;
  
  // Track item quantities sold
  const itemSalesMap: Record<string, { name: string; qty: number; revenue: number }> = {};
  
  dayOrders.forEach(order => {
    netSales += order.total;
    if (order.paymentMethod === "Cash") {
      cashSales += order.total;
      cashCount++;
    } else {
      bakongSales += order.total;
      bakongCount++;
    }
    
    order.items.forEach(item => {
      // Find cost price from master products list fallback
      const originalProduct = products.find(p => p.id === item.productId);
      const itemCost = originalProduct ? originalProduct.costPrice : 0;
      cogs += (item.quantity * itemCost);
      
      const pricePaid = item.sellPrice * (1 - (item.discountPercent || 0) / 100);
      const revenue = item.quantity * pricePaid;
      
      if (itemSalesMap[item.productId]) {
        itemSalesMap[item.productId].qty += item.quantity;
        itemSalesMap[item.productId].revenue += revenue;
      } else {
        itemSalesMap[item.productId] = {
          name: item.productName,
          qty: item.quantity,
          revenue: revenue
        };
      }
    });
  });
  
  const grossProfit = netSales - cogs;
  const profitMarginPercent = netSales > 0 ? (grossProfit / netSales) * 100 : 0;
  const avgBasket = totalOrders > 0 ? netSales / totalOrders : 0;
  const khrExchange = settings.exchangeRate || 4100;
  const salesKHR = netSales * khrExchange;

  // Format Top Selling Items (max 5)
  const topItems = Object.values(itemSalesMap)
    .sort((a, b) => b.qty - a.qty)
    .slice(0, 5);
    
  // Check low stock products
  const lowStockItems = products.filter(p => p.stock <= p.lowStockThreshold);

  // Build the message
  let msg = `📊 <b>DAILY SALES REPORT</b>\n`;
  msg += `📅 Date: <b>${dateStr}</b>\n`;
  msg += `🏪 Store: <b>${settings.merchantName || "My POS Store"}</b>\n`;
  msg += `━━━━━━━━━━━━━━━━━\n\n`;
  
  msg += `📈 <b>FINANCIAL SUMMARY</b>\n`;
  msg += `▪️ Net Sales: <b>$${netSales.toFixed(2)}</b> (<i>~${Math.round(salesKHR).toLocaleString()} KHR</i>)\n`;
  msg += `▪️ Total Orders: <b>${totalOrders}</b>\n`;
  msg += `▪️ Average Basket: <b>$${avgBasket.toFixed(2)}</b>\n`;
  msg += `▪️ Est. COGS: <b>$${cogs.toFixed(2)}</b>\n`;
  msg += `▪️ Est. Gross Profit: <b>$${grossProfit.toFixed(2)}</b> (<i>${profitMarginPercent.toFixed(1)}%</i>)\n\n`;
  
  msg += `💳 <b>PAYMENT BREAKDOWN</b>\n`;
  msg += `▪️ Cash Sales: <b>$${cashSales.toFixed(2)}</b> (<i>${cashCount} sales</i>)\n`;
  msg += `▪️ Bakong KHQR: <b>$${bakongSales.toFixed(2)}</b> (<i>${bakongCount} sales</i>)\n\n`;
  
  msg += `🏷️ <b>TOP SELLING ITEMS</b>\n`;
  if (topItems.length === 0) {
    msg += `<i>No items sold today.</i>\n\n`;
  } else {
    topItems.forEach((item, index) => {
      msg += `${index + 1}. ${item.name}\n   └ <b>${item.qty} sold</b> · Revenue: $${item.revenue.toFixed(2)}\n`;
    });
    msg += `\n`;
  }
  
  msg += `⚠️ <b>LOW STOCK ALERTS</b>\n`;
  if (lowStockItems.length === 0) {
    msg += `✅ <i>All item stock levels are healthy!</i>\n`;
  } else {
    const visibleAlerts = lowStockItems.slice(0, 8);
    visibleAlerts.forEach(p => {
      msg += `▪️ ${p.name}\n   └ Stock: <b>${p.stock}</b> (Threshold: ${p.lowStockThreshold})\n`;
    });
    if (lowStockItems.length > 8) {
      msg += `▪️ <i>And ${lowStockItems.length - 8} other items...</i>\n`;
    }
  }
  
  msg += `\n━━━━━━━━━━━━━━━━━\n`;
  msg += `<i>Generated by ${settings.storeLabel || "Register"} · Always Admin</i>`;
  
  return msg;
}

/**
 * Sends a HTML message using the Telegram Bot API
 */
export async function sendTelegramNotification(botToken: string, chatId: string, text: string): Promise<{ success: boolean; error?: string }> {
  if (!botToken || !chatId) {
    return { success: false, error: "Bot token and Chat ID are required values." };
  }
  
  // Clean token just in case
  const token = botToken.trim();
  const chat = chatId.trim();
  
  const url = `https://api.telegram.org/bot${token}/sendMessage`;
  
  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        chat_id: chat,
        text: text,
        parse_mode: "HTML"
      })
    });
    
    const data = await response.json();
    if (data.ok) {
      return { success: true };
    } else {
      return { success: false, error: data.description || "Telegram API rejected the payload." };
    }
  } catch (err: any) {
    return { success: false, error: err.message || "Failed to make network request to Telegram endpoint." };
  }
}
